config/routes.rb
Kadencer::Application.routes.draw do

  resources :projects

  resources :organizations
  match 'organizations/add_user', :to => 'organizations#add_user'  
  
  devise_for :users
  
  root :to => "home#index"
  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  
    has_and_belongs_to_many :users
    belongs_to :owner, :foreign_key => "owner", :class_name => "User"
    
    validates_presence_of :name, :site_name, :owner
    validates_uniqueness_of :site_name, :case_sensitive => false    

    def self.of_owner(owner_id)
      Organization.where(['owner = ?', owner_id]).first
    end
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates_presence_of :name
  belongs_to :organization
  validates_presence_of :organization_id
  
  def self.of_user(user_id)
    Project.all(:joins => "inner join organizations_users ou on ou.organization_id = projects.organization_id and ou.user_id = #{user_id}")
  end  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :subdomain, :fullName
  
  has_and_belongs_to_many :organizations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    if current_user.organizations.size == 0
      redirect_to "/organizations/new"
    else
      redirect_to "/projects"
    end
  end
  
end

app/controllers/organizations_controller.rb
class OrganizationsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :js
  actions :show, :new, :edit
  
  def create    
     @organization = Organization.new(params[:organization])
     @organization.users << current_user
     @organization.owner = current_user

      respond_to do |format|
        if @organization.save
          format.html { redirect_to root_url }
        else
          format.html { render :action => "new" }
        end
      end
  end
  
  def edit
    @organization = Organization.find(params[:id])
    if @organization.owner.id == current_user.id then
      respond_to do |format|
         format.html { render :action => "edit" }
       end
     else
       flash[:alert] = 'Only the organization owner can edit the organization'
       redirect_to "/projects"
    end
  end
  
  def add_user 
    @user = User.find_by_email(params[:new_user])
    @organization = Organization.find_by_owner(current_user.id)
    respond_to do |format|
      format.js { render :action => "add_user" }
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :html, :js 
  actions :show, :new, :index, :edit, :destroy, :update
  
  def index    
    projects = Project.of_user(current_user.id)
    @projects_map = {}
    projects.each { |p|
      if (!@projects_map[p.organization_id]) then
          @projects_map[p.organization_id] = []
      end
      @projects_map[p.organization_id] << p            
    }    
  end
  
  def new
    @organization = Organization.of_owner(current_user.id)
    puts @organization.name
    super
  end
  
  def edit
    @organization = Organization.of_owner(current_user.id)
    @project = Project.find(params[:id])
    if @project.organization.owner.id == current_user.id then      
      respond_to do |format|       
         format.html { render :action => "edit" }
       end
     else
       flash[:alert] = 'Only the organization owner can edit the project'
       redirect_to "/projects"
    end    
  end
    
  def create
    @project = Project.new(params[:project])    
    @project.organization = Organization.find(params[:organization_id])
       if @project.organization.owner != current_user
         flash[:alert] = 'Only the organization owner can create a project'         
         redirect_to @project
       elsif @project.save
         respond_to do |format|       
            format.html { render :action => "show" }
          end
       else
         respond_to do |format|       
           format.html { render :action => "new" }
         end
       end     
  end
  
  def destroy
    @project = Project.find(params[:id])
    if @project.organization.owner.id == current_user.id then
      @project.destroy
      respond_to do |format|
        format.html { redirect_to(projects_url) }
      end
    else
      flash[:alert] = 'Only the organization owner can delete the project'
      redirect_to "/projects"
    end    
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organization_helper.rb
module OrganizationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<p>teste</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kadencer</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/organizations/add_user.js.erb
{
	"fullName": "<%= @user.fullName %>"
}

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<p id="organization">
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Owner:</b>
  <%= @organization.owner.email %>
</p>

<div id="users">
	<b>Users:</b>
	<ul>
		<% @organization.users.each { |user| %>
			<li><%= user.fullName %></li>
		<% } %>
	</ul>
</div>

<div class="new_user">
	<% form_tag url_for(:action => "add_user"), :id => "form_add_user", :remote => true, "data-type" => "json" do %>			
		<%= hidden_field_tag(:organization_id, @organization.id) %>
		<b>Add User:</b>
		<%= text_field_tag(:new_user) %>
		<button type="submit">Add</button>				
	<% end %>
</div>

<script>
	$('#form_add_user').bind('ajax:success', function(evt, data, status, xhr){
		alert('sucesso');
		alert(data.fullName);
	}).bind('ajax:failure', 	function(evt, data, status, xhr){
		alert('falha');
	});
</script>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/new.html.erb
<h1>Create your Organization</h1>

<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this <%= t('organizations.organization') %> from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_name %><br />
    <%= f.text_field :site_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :has_iterations %><br />
    <%= f.check_box :has_iterations %>
  </div>

	<div class="field">
	    <%= t('organizations.organization') %><br />
	    <b><%= @organization.name %></b>
		<%= hidden_field_tag(:organization_id, @organization.id) %>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Has iterations</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects_map.each_pair do |organization, projects| %>
	<tr class="highlight" id="organization_<%= organization %>">
		<th colspan="4">
			<%= link_to projects[0].organization.name, :controller => "organizations", :action => "edit", :id => projects[0].organization.id %>
		</th>
	</tr>
	<% projects.each do |project| %>
	  <tr>
	    <td><%= project.name %></td>
	    <td><%= project.has_iterations %></td>
	    <td><%= link_to 'Show', project %></td>
	    <td><%= link_to 'Edit', edit_project_path(project) %></td>
	  </tr>
	<% end %>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Has iterations:</b>
  <%= @project.has_iterations %>
</p>

<p id="organization">
  <b>Organization:</b>
  <%= @project.organization.name %>
</p>

<div id="users">
	<p>
		<b>Users:</b>
		<ul>
			<% @project.organization.users.each { |user| %>
				<li><%= user.fullName %></li>
			<% } %>
		</ul>
	</p>
</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>